# Generated by Django 3.1.1 on 2021-08-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, upload_to='static/audio/'),
        ),
    ]
