#!/bin/bash

# EXECUTION:
# 'bash deployment_scripts/deploy'

cd /var/www/wellfort

supervisord -c /etc/supervisord.conf

git pull

sudo mkdir -p logs

pip3 install -r requirements.txt

python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py cron --name audio

cp -r /var/www/wellfort/web/dist/wellfort/* /var/www/html/

supervisorctl restart all
