#!/bin/bash

# EXECUTION:
# 'bash deployment_scripts/deploy'

git pull

sudo mkdir -p logs

pip3 install -r requirements.txt

python3 manage.py makemigrations

python3 manage.py migrate

supervisorctl restart all
